# Generated by Django 6.0.5 on 2026-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_escrowtransaction_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='dispute_resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='dispute_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
