# Generated by Django 6.0.5 on 2026-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_disputeevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='auto_released',
            field=models.BooleanField(default=False, help_text='Whether the booking was auto‑released after 72h without move‑in'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty deducted from escrow if booking expires without move‑in', max_digits=10),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='penalty_applied',
            field=models.BooleanField(default=False, help_text='Whether the penalty has been deducted'),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Payment Received (Held)'), ('released', 'Released to Landlord'), ('refunded', 'Refunded to Tenant'), ('disputed', 'Disputed'), ('auto_released', 'Auto‑Released (No Move‑in)')], default='pending', max_length=20),
        ),
    ]
