# Generated by Django 6.0.5 on 2026-06-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_escrowtransaction_auto_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowtransaction',
            name='dispute_resolution_notes',
            field=models.TextField(blank=True, help_text='Admin notes for refund or dispute resolution', null=True),
        ),
    ]
