# Generated by Django 6.0.5 on 2026-06-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
