# Generated by Django 6.0.5 on 2026-06-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_kyc_document_user_kyc_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
    ]
