# Generated by Django 6.0.5 on 2026-05-27 06:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address_text', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=100)),
                ('estate', models.CharField(blank=True, max_length=100)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('furnished', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=True)),
                ('has_electricity', models.BooleanField(default=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('listing_fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['town', 'rent'], name='properties__town_5f7176_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location'], name='properties__locatio_2b40b0_idx'),
        ),
    ]
