# Generated by Django 6.0.5 on 2026-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a walkthrough video (MP4, max 50MB)', null=True, upload_to='property_videos/'),
        ),
    ]
