# Generated by Django 6.0.5 on 2026-05-27 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_county_property_pets_allowed_property_wifi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedrooms'), ('3br', '3 Bedrooms'), ('studio', 'Studio'), ('other', 'Other')], max_length=20)),
                ('unit_number', models.CharField(blank=True, help_text='e.g., A101, Flat 12', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('booked', 'Booked (pending move-in)'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('available_from', models.DateField(default=django.utils.timezone.now)),
                ('booking_expires', models.DateTimeField(blank=True, help_text='If booked, expiry of booking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_units', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
        ),
    ]
