# Generated by Django 6.0.5 on 2026-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='property_type',
            field=models.CharField(choices=[('rental', 'Long‑term Rental'), ('bnb', 'Bed & Breakfast'), ('lodging', 'Lodging (daily)'), ('short_stay', 'Short‑stay (weekly)')], default='rental', max_length=20),
        ),
    ]
