# Generated by Django 6.0.5 on 2026-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_city_property_formatted_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='booking_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
