# Generated by Django 6.0.5 on 2026-06-12 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_scamreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_verified'], name='properties__is_veri_17d9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured'], name='properties__is_feat_9e46bd_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='properties__bedroom_6cd35c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rent'], name='properties__rent_bbfaca_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_verified', 'created_at'], name='properties__is_veri_b12274_idx'),
        ),
    ]
