# Generated by Django 6.0.5 on 2026-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_properties__created_72ecc3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingappointment',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
