# Generated by Django 6.0.5 on 2026-06-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_viewingappointment_checked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingappointment',
            name='unit',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.PROTECT, to='properties.unit'),
            preserve_default=False,
        ),
    ]
