# Generated by Django 6.0.5 on 2026-06-18 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_viewingappointment_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_number__isnull', False)), fields=('property', 'unit_number'), name='unique_unit_number_per_property'),
        ),
    ]
