# Generated by Django 6.0.5 on 2026-06-19 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_agent_alter_property_landlord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='savedproperty',
            options={'verbose_name_plural': 'Saved Properties'},
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__town_5f7176_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__rent_bbfaca_idx',
        ),
        migrations.AlterUniqueTogether(
            name='favoriteestate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(help_text='Maximum bedroom count available in this property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['town'], name='properties__town_4d50de_idx'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='unique_amenity_per_property'),
        ),
        migrations.AddConstraint(
            model_name='favoriteestate',
            constraint=models.UniqueConstraint(fields=('tenant', 'estate', 'town'), name='unique_tenant_estate_town'),
        ),
        migrations.AddConstraint(
            model_name='savedproperty',
            constraint=models.UniqueConstraint(fields=('tenant', 'property'), name='unique_tenant_saved_property'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent',
        ),
    ]
