# Generated by Django 6.0.5 on 2026-06-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_amenity_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties__locatio_2b40b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__bedroom_6cd35c_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_electricity',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_security',
        ),
        migrations.RemoveField(
            model_name='property',
            name='has_water',
        ),
        migrations.RemoveField(
            model_name='property',
            name='service_charge',
        ),
    ]
