# Generated by Django 6.0.5 on 2026-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_remove_property_properties__locatio_2b40b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
