# Generated by Django 6.0.5 on 2026-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='furnished',
            field=models.BooleanField(default=False, help_text='Is this unit fully furnished?'),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_electricity',
            field=models.BooleanField(default=True, help_text='Does this unit have electricity?'),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_parking',
            field=models.BooleanField(default=False, help_text='Does this unit have parking?'),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_security',
            field=models.BooleanField(default=False, help_text='Does this unit have dedicated security?'),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_water',
            field=models.BooleanField(default=True, help_text='Does this unit have water access?'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedrooms'), ('3br', '3 Bedrooms'), ('studio', 'Studio'), ('single', 'Single Room'), ('double', 'Double Room (shared)'), ('short_single', 'Short-stay Single'), ('short_1br', 'Short-stay 1 Bedroom'), ('commercial', 'Commercial / Shop Front'), ('other', 'Other')], max_length=20),
        ),
    ]
