# Generated by Django 6.0.5 on 2026-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_unit_furnished_unit_has_electricity_unit_has_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly service charge for common areas', max_digits=10),
        ),
    ]
