# Generated by Django 6.0.5 on 2026-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_property_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_electricity',
            field=models.BooleanField(default=True, help_text='Does the building have electricity?'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, help_text='Does the building have parking?'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security',
            field=models.BooleanField(default=False, help_text='Does the building have security?'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water',
            field=models.BooleanField(default=True, help_text='Does the building have water supply?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False, help_text='Pets allowed in the building'),
        ),
        migrations.AlterField(
            model_name='property',
            name='wifi',
            field=models.BooleanField(default=False, help_text='Building has Wi-Fi'),
        ),
    ]
