# Generated by Django 6.0.5 on 2026-06-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistentry',
            name='value',
            field=models.CharField(help_text='Enter the phone number, ID number, email, or M-Pesa account (depending on the entry type).', max_length=255, verbose_name='Identifier'),
        ),
    ]
